# Generated by Django 4.1.6 on 2023-02-18 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='NoName', max_length=50, verbose_name='Назва товару')),
                ('preview', models.ImageField(upload_to='products/preview', verbose_name='Превю товару')),
                ('description', models.TextField(default='', max_length=1500, verbose_name='Опис товару')),
                ('price', models.IntegerField(default=50, verbose_name='Ціна')),
                ('number', models.IntegerField(default=1, verbose_name='Кількість')),
            ],
        ),
    ]
