# Generated by Django 4.1.6 on 2023-02-21 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_delete_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default='uncategorized', max_length=50, verbose_name='Категорія'),
        ),
    ]
